# Generated by Django 5.1.15 on 2026-09-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IrrigationBlackout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("blackout_date", models.DateField()),
                ("reason", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="irrigation_blackouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="irrigation_blackouts",
                        to="core.zone",
                    ),
                ),
            ],
            options={
                "ordering": ["-blackout_date", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="irrigationblackout",
            constraint=models.UniqueConstraint(
                fields=("zone", "blackout_date"), name="uniq_blackout_date_per_zone"
            ),
        ),
    ]
